### ISSUE TITLE
lstpacker.exe seemingly does nothing

### ISSUE THREAD

**Issue by Vinkdicator** [Return-To-The-Roots/libsiedler2#12]
Hi, I tried to use lstpacker.exe according to the instructions for editing fonts but when I drag OUTLINE_FONTS.LST onto it the cmd opens, writes nothing then promptly closes. I cannot see any new folders having been created and the screeds of text on Spike's old video "How to - upack .lst/.lbm/.bbm files using the lstpacker - Windows (RttR)" definitely didn't appear.

**Comment by Spikeone** [comment]
Can you please open the lstpacker in a new cmd window and check the output?

Should look something like this:
![image](https://user-images.githubusercontent.com/1276342/71620726-cadc1d80-2bcb-11ea-8275-226a42c4d37d.png)

Please make also sure that the lstpacker.exe can write files where you are executing it

**Comment by Vinkdicator** [comment]
Ah good thinking for running it through the command prompt! Turns out that the problem was one of my folder names in the path, "settlers 2". Obviously the lstpacker can't handle spaces in filepaths.

**Comment by Spikeone** [comment]
Great :) Although I had in mind, that this was fixed, or does it work as expected @Flamefire ?

**Comment by Flamefire** [comment]
Erm, that can't be the problem. The screenshot above clearly shows using a path with spaces for both the lstpacker and the target. But I'll double check

**Comment by Flamefire** [comment]
Ah yes, this is https://github.com/boostorg/program_options/issues/69 -.-

Fixing...

**Comment by Flamefire** [comment]
Fixed in 1.0.1

**Comment by Spikeone** [comment]
Yeah sorry about the screenshot @Flamefire - was an old lstpacker, pre boost, maybe thats why it worked :D
