### ISSUE TITLE
Upacking and packing does not result in a usable file

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/libsiedler2#19]
I simply unpacked and packed the ROM_Z.LST and it looks like offsets aren't honored at all:
![grafik](https://user-images.githubusercontent.com/1276342/161379700-4be7dcc7-cbb7-4fe9-9d3b-6a2ffb7fd7fd.png)

**Comment by Spikeone** [comment]
Having a look t the names, it looks like someone might forgot to replace an x with an y, as the files each have the same nx and ny ```255.rle.nx39.ny39.bmp```

**Comment by Flow86** [comment]
this is already fixed in code (c7097f685), but was not yet released. I'll create a new lstpacker release v1.1.4 for it

**Comment by Spikeone** [comment]
> this is already fixed in code ([c7097f6](https://github.com/Return-To-The-Roots/libsiedler2/commit/c7097f6857d7f8eea5f33010aacd36d2ce27c2df)), but was not yet released. I'll create a new lstpacker release v1.1.4 for it

Oh, uhm, sorry :x
